### ISSUE TITLE
Add alert to TimeSeries Panel

### ISSUE THREAD

**Issue by RorFis** [grafana/grafonnet#88] opened 2023-07-21 14:42 UTC
I can't find anything to add alerts to a TimeSeries panel. Is it possible ?

**Comment by malcolmholmes** [comment] 2023-07-23 17:53
Alerts are no-longer tied to panels, they need to be created independently. We haven't addressed alerts in this library yet.

**Comment by RorFis** [comment] 2023-07-24 07:47
Any idea on when this will be addressed ?

**Comment by Duologic** [comment] 2023-07-24 08:06
Not yet.

Closing as duplicate of #69

**Closed by Duologic** 2023-07-24 08:06 UTC
